### ISSUE TITLE
BCL is currently down

### ISSUE THREAD

**Issue by macumber** [BuildingComponentLibrary/bcl-manifest#27]
It seems like the BCL (or at least the legacy API endpoints) are currently down.  This url https://bcl.nrel.gov/api/search/denver.json?page=2&show_rows=10&api_version=2.0 is giving an "Internal Server Error" error

**Comment by kflemin** [comment]
@macumber, hi! thanks for reporting. it is back up as of today...but let me know if it's still not working for you!

**Comment by macumber** [comment]
Thanks @kflemin it's working for me, I hope all is well and thanks again!
